### ISSUE TITLE
Loading SVG files fails

### ISSUE THREAD

**Issue by manyids2** [jupyterlab/theme-cookiecutter#2] opened 2019-02-10 12:15 UTC
I think the cookiecutter version only serves files in the root, while icons, etc are deeper down, also
perhaps missing some types (svg, png, etc)
From package.json:

```
cookiecutter version:
    "style/*.css",
    "style/*.ttf",
    "style/*.eot",
    "style/*.woff",
    "style/*.woff2"
```

```
theme-light-extension version:
    "style/**/*.{css,eot,gif,html,jpg,json,png,svg,woff2,ttf}"

```

**Comment by telamonian** [comment] 2019-02-16 23:33
This is a duplicate of the issue discussed in jupyterlab/theme-cookiecutter-ts#5

**Closed as completed by telamonian** 2019-02-16 23:33 UTC
